-- Privacy inquiries lodged from the PRE-AUTH Privacy Policy screen (ADR-091).
--
-- THE SENDER HAS NO ACCOUNT AND NO TENANT, which is why this table exists at all. The two routes that
-- already take a request from a data subject both need something this sender does not have:
-- `platform.export_requests` (20260804000003) is keyed by `user_id`, and `platform.subject_requests`
-- (20260816000003) is tenant-scoped with `opened_by` a NOT NULL FK to platform.users — it records a
-- TENANT'S handling of a request the tenant received off-platform. A reader on the pre-auth policy
-- screen may not even know which organisation here holds their data.
--
-- NO tenant_id AND NO RLS, DELIBERATELY. RLS is the tenant-isolation mechanism (spec §7.7) and there
-- is no tenant to isolate by; the standard policy shape
-- `tenant_id = NULLIF(current_setting('app.current_tenant_id', TRUE), '')::uuid` would deny every row
-- on a request that has no tenant context set. Master §Phase 2 permits this explicitly — "tenant_id
-- UUID NOT NULL on every domain table (platform tables exempt)" and, of the identity tables,
-- "cross-tenant, no RLS needed". Access is confined by ROLE instead: SYSTEM_ADMIN only, through
-- RolesGuard, with every read audited (spec §06 audit-access matrix).
--
-- THIS IS THE FIRST platform TABLE WITHOUT tenant_id. Tooling that assumes every platform row carries
-- one must be checked before it is pointed here (ADR-091 Consequences).
--
-- IT CHAINS INTO subject_requests RATHER THAN DUPLICATING IT. Once an inquiry is matched to a tenant,
-- that tenant's admin opens a subject_requests row in the normal way and `linked_request_id` points
-- at it. That FK is the join between "a stranger wrote to the platform" and "a controller is
-- answering under §30" — two different events with two different clocks.
--
-- Backward-compatible (QM-9): new types + new table only. Nothing existing is touched.
-- Rollback: prisma/rollbacks/20260817000001_privacy_inquiries.rollback.sql

-- The categories the form offers (mockup 07_data_protection_contact's select).
CREATE TYPE platform."PrivacyInquiryCategory" AS ENUM (
  'GENERAL',
  'DATA_ACCESS',
  'DATA_CORRECTION',
  'DATA_DELETION',
  'SECURITY_CONCERN'
);

CREATE TYPE platform."PrivacyInquiryStatus" AS ENUM ('OPEN', 'ROUTED', 'CLOSED');

CREATE TABLE IF NOT EXISTS platform.privacy_inquiries (
  inquiry_id     UUID                              PRIMARY KEY DEFAULT gen_random_uuid(),

  -- The handle the sender is given and can quote back. Human-shaped on purpose: it is read off a
  -- screen and typed into an email, so it is not the UUID. Generated by the application rather than a
  -- sequence so it carries no count — a monotonic reference published to the public would disclose
  -- how many inquiries the platform receives.
  reference      VARCHAR(32)                       NOT NULL UNIQUE,

  -- What the sender told us about themselves. Supplied by an unauthenticated stranger and therefore
  -- UNVERIFIED — the column names say what they are, and nothing downstream may treat them as proof
  -- of identity (GDPR Art 12(2)/12(6): over-verification is itself an infringement).
  -- @pdpa(category: "identity", role: "controller") — a name given by a person with no account here
  sender_name    VARCHAR(255)                      NOT NULL,
  -- @pdpa(category: "contact", role: "controller") — the address a reply goes to
  sender_email   VARCHAR(255)                      NOT NULL,
  -- @pdpa(category: "contact", role: "controller") — optional; the form marks it optional too
  sender_phone   VARCHAR(50),

  category       platform."PrivacyInquiryCategory" NOT NULL DEFAULT 'GENERAL',
  subject        VARCHAR(255)                      NOT NULL,
  -- @pdpa(category: "operational", role: "controller") — free text written by the sender
  message        TEXT                              NOT NULL,

  status         platform."PrivacyInquiryStatus"   NOT NULL DEFAULT 'OPEN',
  received_at    TIMESTAMPTZ                       NOT NULL DEFAULT now(),

  -- Set when SYSTEM_ADMIN matches the inquiry to a tenant and that tenant opens a subject request.
  -- ON DELETE SET NULL: the subject request is the controller's record and may be removed on its own
  -- retention schedule; losing it must not delete the evidence that a stranger wrote in.
  linked_request_id UUID REFERENCES platform.subject_requests (request_id) ON DELETE SET NULL,

  closed_at      TIMESTAMPTZ,
  -- What was done. Required on close, for the same reason subject_requests requires it: a refusal
  -- that does not name its basis is itself a breach (ADR-090 §5).
  outcome_note   TEXT,

  -- A closed inquiry must say what happened; an open one must not pretend it has.
  CONSTRAINT privacy_inquiries_closed_has_outcome
    CHECK ((status = 'CLOSED' AND closed_at IS NOT NULL AND outcome_note IS NOT NULL)
        OR (status <> 'CLOSED' AND closed_at IS NULL)),
  -- ROUTED means "handed to a tenant" — it is not routed anywhere without the pointer that says where.
  CONSTRAINT privacy_inquiries_routed_has_link
    CHECK (status <> 'ROUTED' OR linked_request_id IS NOT NULL)
);

-- The triage queue: oldest first, filtered by status.
CREATE INDEX IF NOT EXISTS privacy_inquiries_status_received_idx
  ON platform.privacy_inquiries (status, received_at);

-- Finding every inquiry from one sender — the first thing an operator does when a person writes twice.
CREATE INDEX IF NOT EXISTS privacy_inquiries_sender_email_idx
  ON platform.privacy_inquiries (sender_email);
