// Guard on the one value that reaches a shell in enterprise-provisioning.activities.
//
// migrateDataActivity runs `pg_dump ... --where="tenant_id='${tenantId}'" | psql ...`. The pipe
// means it goes through /bin/sh, so before this guard a tenantId carrying a quote or `$(...)` was
// arbitrary command execution — with the database URL, credentials and all, in the same string.
// Found by CodeQL js/indirect-command-line-injection.
//
// The activity itself is excluded from the coverage gate (it provisions real infrastructure and
// cannot run under jest), which is precisely why the guard was pulled out as a pure function.

import { assertShellSafeDbUrl, assertUuid } from '../workflows/enterprise-provisioning.activities';

describe('assertUuid', () => {
  it.each([
    ['a v4 UUID', '3f2504e0-4f89-41d3-9a0c-0305e82c3301'],
    ['an uppercase UUID', '3F2504E0-4F89-41D3-9A0C-0305E82C3301'],
    ['a nil UUID', '00000000-0000-0000-0000-000000000000'],
  ])('accepts %s', (_label, value) => {
    expect(() => assertUuid(value, 'tenantId')).not.toThrow();
  });

  it.each([
    ['a shell-quote break-out', "3f2504e0-4f89-41d3-9a0c-0305e82c3301'; rm -rf /; #"],
    ['command substitution', '$(id)'],
    ['backtick substitution', '`id`'],
    ['a pipe', 'abc | cat /etc/passwd'],
    ['a semicolon', 'abc; whoami'],
    ['a UUID with trailing junk', '3f2504e0-4f89-41d3-9a0c-0305e82c3301x'],
    ['a UUID with a leading space', ' 3f2504e0-4f89-41d3-9a0c-0305e82c3301'],
    ['a truncated UUID', '3f2504e0-4f89-41d3-9a0c'],
    ['an empty string', ''],
  ])('rejects %s', (_label, value) => {
    expect(() => assertUuid(value, 'tenantId')).toThrow('tenantId must be a UUID');
  });

  it('names the offending field and does not echo the value back', () => {
    // The value can contain attacker-controlled text; it has no business in the error message.
    expect(() => assertUuid('$(id)', 'rdsEndpoint')).toThrow('rdsEndpoint must be a UUID');
    expect(() => assertUuid('$(id)', 'rdsEndpoint')).not.toThrow(/\$\(id\)/);
  });
});

describe('assertShellSafeDbUrl', () => {
  // The two connection URLs are interpolated into the same shell command. They come from config
  // rather than a request, but a password generated by Secrets Manager is not a safe string: one
  // containing a backtick or `$(` would execute. CodeQL js/indirect-command-line-injection.
  it.each([
    ['a plain URL', 'postgres://app:pw@db.internal:5432/cos'],
    ['the postgresql:// scheme', 'postgresql://app:pw@db.internal:5432/cos'],
    ['a password with URL-safe punctuation', 'postgres://app:a-b_c.d~e@db:5432/cos'],
    ['query parameters', 'postgres://app:pw@db:5432/cos?sslmode=require'],
  ])('accepts %s', (_label, url) => {
    expect(() => assertShellSafeDbUrl(url, 'DATABASE_URL')).not.toThrow();
  });

  it.each([
    ['command substitution in the password', 'postgres://app:$(id)@db:5432/cos'],
    ['a backtick in the password', 'postgres://app:`id`@db:5432/cos'],
    ['a quote in the password', 'postgres://app:p"w@db:5432/cos'],
    ['a single quote in the password', "postgres://app:p'w@db:5432/cos"],
    ['a pipe', 'postgres://app:pw@db:5432/cos|whoami'],
    ['a semicolon', 'postgres://app:pw@db:5432/cos;whoami'],
    ['an ampersand', 'postgres://app:pw@db:5432/cos&id'],
    ['a redirect', 'postgres://app:pw@db:5432/cos>/tmp/x'],
    ['a backslash', 'postgres://app:p\\w@db:5432/cos'],
    ['whitespace', 'postgres://app:pw@db:5432/cos --help'],
    ['a newline', 'postgres://app:pw@db:5432/cos\nrm -rf /'],
  ])('rejects %s', (_label, url) => {
    expect(() => assertShellSafeDbUrl(url, 'DATABASE_URL')).toThrow('unsafe in a shell command');
  });

  it.each([
    ['an http URL', 'http://db:5432/cos'],
    ['a bare host', 'db.internal:5432'],
    ['an empty string', ''],
  ])('rejects %s as not a postgres URL', (_label, url) => {
    expect(() => assertShellSafeDbUrl(url, 'DATABASE_URL')).toThrow('must be a postgres:// URL');
  });
});
