{{- if .Values.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "cos-analytics-worker.fullname" . }}
  labels: {{ include "cos-analytics-worker.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels: {{ include "cos-analytics-worker.selectorLabels" . | nindent 6 }}
{{- end }}
