// Ed25519 crypto test vectors (CS-9) — deterministic regression lock on the signing pipeline.
//
// Ed25519 (RFC 8032) is deterministic: a fixed 32-byte seed yields a fixed keypair, and signing a fixed
// message yields a fixed signature. The golden anchors below are the (non-secret) public key + signature
// generated by @digitalbazaar/ed25519-verification-key-2020 for the seed 0x00..0x1f. The private key is
// DERIVED from the seed at runtime — never embedded as a literal (a private-key literal is a secret the
// QM-4 scanner correctly rejects). If a dependency bump changes key derivation or the signature bytes,
// these assertions fail loudly.
//
// No DB / network — pure crypto, so this runs in the normal unit + coverage gate.
import { Ed25519VerificationKey2020 } from '@digitalbazaar/ed25519-verification-key-2020';
import { buildDidKeySuite, issueCredential, verifyCredential } from '../vc-service.js';

const SEED = new Uint8Array(32);
for (let i = 0; i < 32; i++) SEED[i] = i; // 0x00, 0x01, … 0x1f

const PUBLIC_KEY_MULTIBASE = 'z6MkehRgf7yJbgaGfYsdoAsKdBPE3dj2CYhowQdcjqSJgvVd';
const MESSAGE = new TextEncoder().encode('cos-credential-service:ed25519-vector:v1');
const SIGNATURE_HEX =
  'efca97d07b742be6d66e1654f4701761d8f6e91dcf2fdad9d34b5901f91dd034' +
  '7bbcd8b9ff479fa557dc34f74d0bc9078ab942296a9014e38dec992f89203f06';

/** Derive the deterministic keypair from the fixed seed (private material stays in-process only). */
function keyFromSeed(): Promise<InstanceType<typeof Ed25519VerificationKey2020>> {
  return Ed25519VerificationKey2020.generate({ seed: SEED });
}

describe('Ed25519 crypto vectors (CS-9)', () => {
  it('derives a deterministic keypair from a fixed seed', async () => {
    const key = await keyFromSeed();
    expect(key.publicKeyMultibase).toBe(PUBLIC_KEY_MULTIBASE);
    // Private-key derivation is deterministic — re-derive and compare, so no secret is embedded in source.
    const again = await keyFromSeed();
    expect(again.privateKeyMultibase).toBe(key.privateKeyMultibase);
  });

  it('produces the golden signature, verifies it, and rejects a tampered signature', async () => {
    const key = await keyFromSeed();
    const signature = await key.signer().sign({ data: MESSAGE });
    expect(Buffer.from(signature).toString('hex')).toBe(SIGNATURE_HEX);

    const verifier = key.verifier();
    expect(await verifier.verify({ data: MESSAGE, signature })).toBe(true);

    const tampered = Uint8Array.from(signature);
    tampered[0] ^= 0x01;
    expect(await verifier.verify({ data: MESSAGE, signature: tampered })).toBe(false);
  });

  it('round-trips the fixed key through the full VC issue → verify pipeline', async () => {
    const key = await keyFromSeed();
    const { suite, did } = await buildDidKeySuite({
      publicKeyMultibase: key.publicKeyMultibase,
      privateKeyMultibase: key.privateKeyMultibase,
    });
    // did:key encodes the Ed25519 public key → the multibase IS the method-specific id.
    expect(did).toBe(`did:key:${PUBLIC_KEY_MULTIBASE}`);

    const signed = await issueCredential({
      suite,
      issuerDid: did,
      subjectId: 'did:example:subject',
      issuanceDate: '2026-07-20T00:00:00Z',
    });
    expect((await verifyCredential(signed)).verified).toBe(true);
  });
});
