replicaCount: 3
resources:
  requests:
    cpu: '1000m'
    memory: '2Gi'
  limits:
    cpu: '4000m'
    memory: '8Gi'
autoscaling:
  minReplicas: 3
  maxReplicas: 12
podDisruptionBudget:
  minAvailable: 2
