import { Injectable, InternalServerErrorException, UnauthorizedException } from '@nestjs/common';
import { createLogger } from '@cos/logger';

const logger = createLogger('keycloak-admin-service');

export interface KeycloakTokenResponse {
  access_token: string;
  refresh_token: string;
  expires_in: number;
  refresh_expires_in: number;
  token_type: string;
}

@Injectable()
export class KeycloakAdminService {
  private readonly baseUrl: string;
  private readonly clientId: string;
  private readonly clientSecret: string;

  constructor() {
    this.baseUrl = process.env['KEYCLOAK_URL'] ?? 'http://localhost:8090';
    this.clientId = process.env['KEYCLOAK_ADMIN_CLIENT_ID'] ?? 'cos-backend';
    const secret = process.env['KEYCLOAK_ADMIN_CLIENT_SECRET'];
    // Fail-fast in production: the dev placeholder secret must never be used outside local/dev —
    // production injects the real secret via AWS Secrets Manager / Vault (QM-4).
    if (!secret && process.env['NODE_ENV'] === 'production') {
      throw new Error('KEYCLOAK_ADMIN_CLIENT_SECRET must be set in production');
    }
    this.clientSecret = secret ?? 'cos-backend-secret-dev';
  }

  // @keycloak/keycloak-admin-client is ESM-only and backend compiles to CommonJS
  // (module: Node16). Load it via dynamic import() so tsc never emits a require()
  // of an ES module (TS1479); the return type is inferred from the client instance.
  private async getAuthenticatedClient(realm: string) {
    const { default: KcAdminClientCtor } = await import('@keycloak/keycloak-admin-client');
    const client = new KcAdminClientCtor({ baseUrl: this.baseUrl, realmName: realm });
    await client.auth({
      grantType: 'client_credentials',
      clientId: this.clientId,
      clientSecret: this.clientSecret,
    });
    return client;
  }

  /**
   * Create Keycloak user for Path A (phone/OTP).
   * Called at user creation time. Returns Keycloak UUID to store in platform.users.keycloak_user_id.
   */
  async provisionPhoneUser(
    phone: string,
    displayName: string,
    realm: string,
    tenantId: string,
    userId: string,
    role: string,
  ): Promise<{ keycloakUserId: string }> {
    const client = await this.getAuthenticatedClient(realm);
    const { id } = await client.users.create({
      username: phone,
      firstName: displayName,
      enabled: true,
      attributes: { tenant_id: [tenantId], user_id: [userId], role: [role] },
    });
    logger.info({ userId, tenantId, realm }, 'keycloak.user.created (Path A)');
    return { keycloakUserId: id };
  }

  /**
   * Create Keycloak user for Path B (email/OIDC).
   * Called at user creation time. Returns Keycloak UUID to store in platform.users.keycloak_user_id.
   */
  async createEmailUser(
    email: string,
    displayName: string,
    realm: string,
    tenantId: string,
    userId: string,
    role: string,
  ): Promise<{ keycloakUserId: string }> {
    const client = await this.getAuthenticatedClient(realm);
    const { id } = await client.users.create({
      username: email,
      email,
      firstName: displayName,
      enabled: true,
      attributes: { tenant_id: [tenantId], user_id: [userId], role: [role] },
    });
    logger.info({ userId, tenantId, realm }, 'keycloak.user.created (Path B)');
    return { keycloakUserId: id };
  }

  /**
   * Set an ephemeral credential on a Path A Keycloak user and call Direct Grant.
   * Called at OTP login time. ephemeralCredential is a random UUID generated by caller;
   * it is overwritten on each login, effectively making it one-time-use.
   * Returns RS256 access token + refresh token from Keycloak.
   */
  async exchangeOtpForTokens(
    keycloakUserId: string,
    phone: string,
    realm: string,
    ephemeralCredential: string,
  ): Promise<KeycloakTokenResponse> {
    const client = await this.getAuthenticatedClient(realm);

    await client.users.resetPassword({
      id: keycloakUserId,
      credential: { type: 'password', value: ephemeralCredential, temporary: false },
    });

    return this.callTokenEndpoint(
      realm,
      new URLSearchParams({
        grant_type: 'password',
        client_id: this.clientId,
        client_secret: this.clientSecret,
        username: phone,
        password: ephemeralCredential,
      }),
      'directgrant',
    );
  }

  /** Proxy refresh_token grant to Keycloak. Returns new access + refresh tokens (rotation). */
  async refreshToken(refreshToken: string, realm: string): Promise<KeycloakTokenResponse> {
    return this.callTokenEndpoint(
      realm,
      new URLSearchParams({
        grant_type: 'refresh_token',
        client_id: this.clientId,
        client_secret: this.clientSecret,
        refresh_token: refreshToken,
      }),
      'refresh',
    );
  }

  /** Revoke refresh token at Keycloak logout endpoint. */
  async revokeToken(refreshToken: string, realm: string): Promise<void> {
    const res = await fetch(`${this.baseUrl}/realms/${realm}/protocol/openid-connect/logout`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
      body: new URLSearchParams({
        client_id: this.clientId,
        client_secret: this.clientSecret,
        refresh_token: refreshToken,
      }).toString(),
    });
    if (!res.ok) {
      logger.warn(
        { realm, status: res.status },
        'keycloak.revoke.failed — token may already be expired',
      );
    }
  }

  /**
   * Admin-set a temporary password on a user's Keycloak account (TENANT_ADMIN-triggered reset).
   * temporary=true adds the UPDATE_PASSWORD required action, so Keycloak forces the user to choose a
   * new password at their next sign-in — the value returned to the admin is a one-time handover secret,
   * not a permanent credential. The plaintext is generated by the caller and never persisted by COS.
   */
  async setTemporaryPassword(
    keycloakUserId: string,
    realm: string,
    password: string,
  ): Promise<void> {
    const client = await this.getAuthenticatedClient(realm);
    await client.users.resetPassword({
      id: keycloakUserId,
      credential: { type: 'password', value: password, temporary: true },
    });
    logger.info({ keycloakUserId, realm }, 'keycloak.password.temp_reset');
  }

  /** Delete Keycloak user — rollback on downstream COS DB failure. */
  async deleteUser(keycloakUserId: string, realm: string): Promise<void> {
    const client = await this.getAuthenticatedClient(realm);
    await client.users.del({ id: keycloakUserId });
    logger.info({ keycloakUserId, realm }, 'keycloak.user.deleted');
  }

  private async callTokenEndpoint(
    realm: string,
    params: URLSearchParams,
    operation: string,
  ): Promise<KeycloakTokenResponse> {
    const res = await fetch(`${this.baseUrl}/realms/${realm}/protocol/openid-connect/token`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
      body: params.toString(),
    });

    if (!res.ok) {
      const body = await res.text();
      logger.warn({ realm, status: res.status, body, operation }, 'keycloak.token.failed');
      if (operation === 'refresh') {
        throw new UnauthorizedException('Refresh token invalid or expired');
      }
      throw new InternalServerErrorException('Token endpoint error');
    }

    return res.json() as Promise<KeycloakTokenResponse>;
  }
}
