replicaCount: 3
resources:
  requests:
    cpu: '500m'
    memory: '512Mi'
  limits:
    cpu: '2000m'
    memory: '2Gi'
autoscaling:
  minReplicas: 3
  maxReplicas: 16
podDisruptionBudget:
  minAvailable: 2
